### ISSUE TITLE
subApp.ts 底部有空行时，srcAppGroupName解析出错

### ISSUE THREAD

**Issue by muyiwei** [hel-eco/hel-tpl-remote-lib#1]
subApp.ts 底部有空行时，srcAppGroupName解析出错，导致无法打包成功
![image](https://user-images.githubusercontent.com/14371896/188608725-9320905d-44f1-4892-842f-04307c3c5d7e.png)
![image](https://user-images.githubusercontent.com/14371896/188609086-45def437-eb81-4567-9a45-49e6122409e7.png)

**Comment by fantasticsoul** [comment]
收到bug报告，欢迎提交修复的pr哈，我有空就把它修了

**Comment by fantasticsoul** [comment]
此问题已修复，可升级`hel-dev-utils`到`2.3.3`版本来解决
